#    Copyright 2025 Cognizant Technology Solutions Corp, www.cognizant.com.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

version: "1.0"

steps:
    main_clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "leaf-ai/neuro-san-ui"
        git: "github"
        revision: ${{UNILEAF_VERSION}}

    generate_typescript_api_stubs:
        title: Generate Typescript stubs for APIs
        image: node:${{NODEJS_VERSION}}-alpine
        working_directory: ${{CF_VOLUME_PATH}}/neuro-san-ui
        commands:
            - apk add --quiet --no-progress --upgrade bash git
            - yarn install
            - ./build_scripts/do_openapi_generate.sh

    prebuild:
        title: Run prebuild step for custom build
        description: Pare down the code to build sub-sets of the ui
        image: alpine:3.21.3
        working_directory: ${{CF_VOLUME_PATH}}/neuro-san-ui
        commands:
            - apk --quiet --no-progress add bash git coreutils
            - ./build_scripts/customBuilds/prepare_custom_build.sh

    set_tag:
        title: Set Image Tag
        description: Keep current tag the same for full builds, append for custom builds
        image: alpine:3.21.3
        shell: sh
        commands:
            - |
                # Use DISPLAY_VERSION if set and not triggered as a child pipeline.
                # Otherwise fallback to UNILEAF_VERSION.
                if [ -n "${{DISPLAY_VERSION}}" ] && [ -z "${CHILD_PIPELINE}" ]; then
                    VERSION="${{DISPLAY_VERSION}}"
                else
                    VERSION="${{UNILEAF_VERSION}}"
                fi

                export TAG="${VERSION}"
                cf_export TAG

    ui-node-build:
        title: Build ui-node Docker image
        image_name: "leaf/neuro-san-ui"
        type: build
        buildkit: true
        progress: "plain"
        dockerfile: ./Dockerfile
        working_directory: ./
        build_arguments:
            - NODEJS_VERSION=${{NODEJS_VERSION}}
            - UNILEAF_VERSION=${{TAG}}
        tag: "${{TAG}}"
