version: '1.0'
steps:
    main_clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "leaf-ai/neuro-ui"
        git: "github"
        revision: ${{UNILEAF_VERSION}}

    create-temp-git-creds-from-vault:
        title: "Get ephemeral GitHub creds"
        description: "Get temporary git credentials from vault server."
        type: "freestyle"
        image: "vault:1.12.0"
        commands:
            # Login into Vault only once
            - >-
                vault login -address=${{VAULT}} -method=github token=${{VAULT_LOGIN}}
                | grep -Ev "(token |token_accessor)"
            
            - EPHEMERAL_TOKEN=$(vault read -address=${{VAULT}} -field=token /github-secrets/token/repo-read)
            - cf_export EPHEMERAL_LEAF_SOURCE_CREDENTIALS="x-access-token:${EPHEMERAL_TOKEN}" --mask
            - cf_export LEAF_SOURCE_CREDENTIALS="${EPHEMERAL_TOKEN}" --mask
            
    generate_proto_stubs_for_ui:
      title: Generate proto stubs for ui
      description: Generate proto stubs for the frontend
      image: node:${{NODEJS_VERSION}}-alpine
      working_directory: ${{CF_VOLUME_PATH}}/neuro-ui
      commands:
        - apk add --quiet --no-progress --upgrade bash protobuf-dev git
        - yarn install
        - yarn --cwd embed install
        - ./build_scripts/do_typescript_generate.sh

    ui-node-build:
      title: Build ui-node Docker image
      image_name: "leaf/unileaf-ui-node"
      type: build
      buildkit: true
      progress: "plain"
      dockerfile: ./Dockerfile
      working_directory: ./
      build_arguments:
        - NODEJS_VERSION=${{NODEJS_VERSION}}
        - UNILEAF_VERSION=${{UNILEAF_VERSION}}
      tag: "${{UNILEAF_VERSION}}"
