version: '1.0'
steps:
    main_clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "leaf-ai/neuro-ui"
        git: "github"
        revision: ${{VERSION}}

    prepare_for_build:
        description: "Do any common preparation for tests"
        type: "freestyle"
        image: alpine:3.13.1
        commands:
            - export TEMP_DIR_OUTSIDE_CONTAINER=${{CF_VOLUME_PATH}}/tmp/${{CF_BUILD_ID}}
            - mkdir -p ${TEMP_DIR_OUTSIDE_CONTAINER}
            - cf_export TEMP_DIR_OUTSIDE_CONTAINER

    create-temp-git-creds-from-vault:
        title: "Get ephemeral GitHub creds"
        description: "Get temporary git credentials from vault server."
        type: "freestyle"
        image: "vault:1.12.0"
        commands:
            # Login into Vault only once
            - >-
                vault login -address=${{VAULT}} -method=github token=${{VAULT_LOGIN}}
                | grep -Ev "(token |token_accessor)"
            
            - EPHEMERAL_TOKEN=$(vault read -address=${{VAULT}} -field=token /github-secrets/token/repo-read)
            - cf_export EPHEMERAL_LEAF_SOURCE_CREDENTIALS="x-access-token:${EPHEMERAL_TOKEN}"
            - cf_export LEAF_SOURCE_CREDENTIALS="${EPHEMERAL_TOKEN}"
            - echo ${LEAF_SOURCE_CREDENTIALS} > ${TEMP_DIR_OUTSIDE_CONTAINER}/LEAF_SOURCE_CREDENTIALS.txt
            
    generate_proto_stubs_for_ui:
      title: Generate proto stubs for ui
      description: Generate proto stubs for the frontend
      image: node:${{NODEJS_VERSION}}-alpine
      working_directory: ${{CF_VOLUME_PATH}}/neuro-ui
      commands:
        - apk add --quiet --no-progress --upgrade bash protobuf-dev git
        - yarn install
        - ./grpc/do_typescript_generate.sh

    ui-node-build:
      title: Build ui-node Docker image
      image_name: "leaf/unileaf-ui-node"
      type: build
      buildkit: true
      disable_push: true
      progress: "plain"
      dockerfile: ./Dockerfile
      working_directory: ./
      build_arguments:
        - NODEJS_VERSION=${{NODEJS_VERSION}}
        - UNILEAF_VERSION=${{UNILEAF_VERSION}}
        # Provide either "old" or "new" to switch between
        # model serving versions.
        - MODEL_SERVING_VERSION=${{MODEL_SERVING_VERSION}}
      tag: "${{UNILEAF_VERSION}}"
      secrets:
        - id=LEAF_SOURCE_CREDENTIALS,src=${{TEMP_DIR_OUTSIDE_CONTAINER}}/LEAF_SOURCE_CREDENTIALS.txt

    clean_up:
      description: "Clean up after ourselves"
      type: "freestyle"
      image: alpine:3.13.1
      commands:
        # Clean up anything senstive we do not want to leak between builds
        - rm -rf ${{TEMP_DIR_OUTSIDE_CONTAINER}}

