version: '1.0'
steps:
    main_clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "leaf-ai/neuro-ui"
        git: "github"
        revision: ${{UNILEAF_VERSION}}

    create-temp-git-creds-from-vault:
        title: "Get ephemeral GitHub creds"
        description: "Get temporary git credentials from vault server."
        type: "freestyle"
        image: "vault:1.12.0"
        commands:
            # Login into Vault only once
            - >-
                vault login -address=${{VAULT}} -method=github token=${{VAULT_LOGIN}}
                | grep -Ev "(token |token_accessor)"
            
            - EPHEMERAL_TOKEN=$(vault read -address=${{VAULT}} -field=token /github-secrets/token/repo-read)
            - cf_export EPHEMERAL_LEAF_SOURCE_CREDENTIALS="x-access-token:${EPHEMERAL_TOKEN}" --mask
            - cf_export LEAF_SOURCE_CREDENTIALS="${EPHEMERAL_TOKEN}" --mask
            
    generate_typescript_api_stubs:
      title: Generate Typescript stubs for APIs
      image: node:${{NODEJS_VERSION}}-alpine
      working_directory: ${{CF_VOLUME_PATH}}/neuro-ui
      commands:
        - apk add --quiet --no-progress --upgrade bash protobuf-dev git
        - yarn install
        - ./build_scripts/do_typescript_generate.sh
        - ./build_scripts/do_openapi_generate.sh

    prebuild:
      title: Run prebuild step for custom build
      description: Pare down the code to build sub-sets of the ui
      image: alpine:3.21.3
      working_directory: ${{CF_VOLUME_PATH}}/neuro-ui
      commands:
        - apk --quiet --no-progress add bash git coreutils
        - ./build_scripts/customBuilds/prepare_custom_build.sh

    set_tag:
      title: Set Image Tag
      description: Keep current tag the same for full builds, append for custom builds
      image: alpine:3.21.3
      shell: sh
      commands:
        - |
          if [ -z "${{BUILD_TARGET}}" ] || [ "${{BUILD_TARGET}}" = "all" ]; then
            export TAG="${{UNILEAF_VERSION}}"
          else
            export TAG="${{UNILEAF_VERSION}}-${{BUILD_TARGET}}"
          fi
          cf_export TAG

    ui-node-build:
      title: Build ui-node Docker image
      image_name: "leaf/unileaf-ui-node"
      type: build
      buildkit: true
      progress: "plain"
      dockerfile: ./Dockerfile
      working_directory: ./
      build_arguments:
        - NODEJS_VERSION=${{NODEJS_VERSION}}
        - UNILEAF_VERSION=${{UNILEAF_VERSION}}
      tag: "${{TAG}}"
