/**
 * This file auto-generates OpenAPI types.
 */

import fs from "fs"
import path from "path"
import {Project} from "ts-morph"

const currentDirPath = import.meta.dirname

const autoGenComment = `
/**
 * This file was auto-generated by a tool.
 * Do not make direct changes to the file.
 */`

const componentsImport = "import {components} from './NeuroSanClient'"
const reservedNames = ["Function"]
const project = new Project()
const sourceFile = project.addSourceFileAtPath(path.resolve(currentDirPath, "../generated/neuro-san/NeuroSanClient.ts"))
const interfaceDecl = sourceFile.getInterfaceOrThrow("components")
const schemasProp = interfaceDecl.getPropertyOrThrow("schemas")
const schemasType = schemasProp.getType().getApparentProperties()
const lines = schemasType.map((prop) => {
    const schemaType = prop.getName()
    const exportName = reservedNames.includes(schemaType) ? `_${schemaType}` : schemaType
    return `export type ${exportName} = components["schemas"]["${schemaType}"]`
})

const fileContent = [autoGenComment, componentsImport, ...lines, ""].join("\n")
fs.writeFileSync(path.resolve(currentDirPath, "../generated/neuro-san/OpenAPITypes.ts"), fileContent)
console.log(`Generated ${lines.length} type exports from components.schemas`)
