import fs from "fs"
// eslint-disable-next-line unicorn/import-style
import path, {dirname} from "path"
import {Project} from "ts-morph"
import {fileURLToPath} from "url"

// eslint-disable-next-line no-shadow
const __filename = fileURLToPath(import.meta.url)
// eslint-disable-next-line no-shadow
const __dirname = dirname(__filename)

const autoGenComment = `
/**
 * This file was auto-generated by build_scripts/GenerateOpenAPITypes.ts
 * Do not make direct changes to the file.
 */`

const componentsImport = "import {components} from './NeuroSanClient'"
const reservedNames = ["Function"]
const project = new Project()
const sourceFile = project.addSourceFileAtPath(path.resolve(__dirname, "../generated/neuro-san/NeuroSanClient.ts"))
const interfaceDecl = sourceFile.getInterfaceOrThrow("components")
const schemasProp = interfaceDecl.getPropertyOrThrow("schemas")
const schemasType = schemasProp.getType().getApparentProperties()
const lines = schemasType.map((prop) => {
    const schemaType = prop.getName()
    const exportName = reservedNames.includes(schemaType) ? `_${schemaType}` : schemaType
    return `export type ${exportName} = components["schemas"]["${schemaType}"]`
})

// Remove ts and eslint directive comments
const fileContent = [autoGenComment, componentsImport, ...lines, ""].join("\n")

fs.writeFileSync(path.resolve(__dirname, "../generated/neuro-san/OpenAPITypes.ts"), fileContent)

console.log(`Generated ${lines.length} type exports from components.schemas`)
