/**
 * Controller module for interacting with the Agent LLM API.
 */
import {
    ChatContext,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ConciergeResponse,
    ConnectivityResponse,
    FunctionResponse,
} from "../../components/AgentChat/Types"
import {NEURO_SAN_SERVER_URL} from "../../const"
import {sendLlmRequest} from "../llm/llm_chat"

export async function getAgentNetworks(): Promise<string[]> {
    const path = `${NEURO_SAN_SERVER_URL}/api/v1/list`
    const response = await fetch(path)
    const conciergeResponse: ConciergeResponse = (await response.json()) as ConciergeResponse
    return conciergeResponse.agents.map((network) => network.agent_name)
}

/**
 * Send a chat query to the Agent LLM API. This opens a session with the agent network.
 * @param signal The AbortSignal to use for the request. Used to cancel the request on user demand
 * @param userInput The user input to send to the agent.
 * In practice this "input" will actually be the output from one of the previous agents such as the data generator
 * or scoping agent.
 * @param targetAgent The target agent to send the request to. See CombinedAgentType for the list of available agents.
 * @param callback The callback function to be called when a chunk of data is received from the server.
 * @param chatContext "Opaque" conversation context for maintaining conversation state with the server. Neuro-san
 * agents do not use ChatHistory directly, but rather, ChatContext, which is a collection of ChatHistory objects.
 * @param slyData Data items that should not be send to the LLM. Generated by the server.
 * @returns The response from the agent network.
 */
export async function sendChatQuery(
    signal: AbortSignal,
    userInput: string,
    targetAgent: string,
    callback: (chunk: string) => void,
    chatContext: ChatContext,
    slyData: Record<string, never>
): Promise<ChatResponse> {
    // Create request
    const userMessage: ChatMessage = {
        type: "HUMAN",
        text: userInput,
    }

    const agentChatRequest: ChatRequest = {
        // TODO: Type 'string' is not assignable to type 'never'.
        sly_data: slyData,
        user_message: userMessage,
        chat_filter: {chat_filter_type: "MAXIMAL"},
        chat_context: chatContext,
    }

    const fetchUrl = `${NEURO_SAN_SERVER_URL}/api/v1/${targetAgent.toLocaleLowerCase()}/streaming_chat`
    const requestRecord: Record<string, unknown> = Object.entries(agentChatRequest).reduce(
        (acc, [key, value]) => (value ? {...acc, [key]: value} : acc),
        {}
    )

    return sendLlmRequest(callback, signal, fetchUrl, requestRecord, null)
}

/**
 * Gets information on what a specified agent is connected to (other agents and tools)
 * @param targetAgent The agent to get connectivity information for
 * @returns The connectivity info as a <code>ConnectivityResponse</code> object
 * @throws Various exceptions if anything goes wrong such as network issues or invalid agent type.
 * Caller is responsible for try-catch.
 */
export async function getConnectivity(targetAgent: string): Promise<ConnectivityResponse> {
    const fetchUrl = `${NEURO_SAN_SERVER_URL}/api/v1/${targetAgent.toLocaleLowerCase()}/connectivity`

    const response = await fetch(fetchUrl, {
        method: "GET",
        headers: {
            "Content-Type": "application/json",
        },
    })

    if (!response.ok) {
        console.debug(`response: ${JSON.stringify(response)}`)
        throw new Error(`Failed to send connectivity request: ${response.statusText}`)
    }

    return response.json()
}

/**
 * Get the function of a specified agent meaning its brief description
 * @param targetAgent The agent to get the function for
 * @returns The function info as a <code>FunctionResponse</code> object
 * @throws Various exceptions if anything goes wrong such as network issues or invalid agent type.
 */
export async function getAgentFunction(targetAgent: string): Promise<FunctionResponse> {
    const fetchUrl = `${NEURO_SAN_SERVER_URL}/api/v1/${targetAgent.toLocaleLowerCase()}/function`

    const response = await fetch(fetchUrl, {
        method: "GET",
        headers: {
            "Content-Type": "application/json",
        },
    })

    if (!response.ok) {
        throw new Error(`Failed to send agent function request: ${response.statusText}`)
    }

    return response.json()
}
